# 1 学习内容

## 1.1 异常

Java异常机制的五个关键字：

* try
* catch
* finally
* throw
* throws

## 1.2 try...catch捕获异常

在try中书写正常的处理过程，如果try执行try中的代码时出现异常，系统会自动生成一个异常对象，该异常对象被提交给java运行时环境，这个过程被称为抛出(throw)异常。

当java运行时环境收到异常对象时，会寻找能处理该异常对象的catch块，如果找到合适的catch块，就把该异常对象交给该catch块处理，这个过程被称为捕获异常。如果java运行时环境找不到捕获异常的catch块，则运行时环境终止，java程序也将退出。

```java
try{
    // 正常流程
}catch(Exception e){
    // 处理异常情况
}
```

## 1.3 异常类的继承体系

Java把所有的非正常情况分为两种

* 异常（Exception）

  * SQLException
  * RuntimeException
    * IndexOutOfBoundsException
    * NullPointerException
    * ClassCastException
    * ...
  * IOException

* 错误（Error）

  一般是指与虚拟机相关的问题，如系统崩溃，虚拟机错误，动态连接失败等，这种错误是无法恢复或不可能捕获，将导致应用程序中断。

  通常应用程序无法处理这些错误，因此应用程序不应该使用catch块来捕获Error对象。

这两种情况都继承自Throwable符类。

**一般来说，程序都应该将Exception类放在catch块的最后面。**而且所有父类异常都应该放在子类异常后面。这是因为如果父类异常放在前面，那么后面的子类异常将永远得不到执行。

## 1.4 多异常捕获

从java7之后，一个catch块可以捕获多种异常。

* 多种异常类型之前用 | 隔开
* 异常变量有隐式的final修饰，因此程序不能对异常变量重新赋值。

```shell
try{
	...
}
catch(IndexOutOfBoundsException|NumberFormationException|ArithmeticException ie){
	System.out.println("程序发生了数组越界，数字格式异常，算数异常之一")；
}
catch(Exception e){
	System.out.println("未知异常");
}
```

## 1.5 访问异常信息

如果程序需要在catch中访问异常对象的相关信息，则需要通过访问catch块后的异常形参来获得。java提供了几种方法来获得异常的相关信息。

* getMessage():返回该异常的详细描述字符串
* printStackTrace():将该异常的跟踪栈信息输出到标准错误输出
* printStackTrace(PrintStream s):将该异常的跟踪站信息输出到指定输出流
* getStackTrace():返回该异常的跟踪栈信息。

## 1.6 使用finally回收资源

为了回收try中打开的资源，java提供了finally块，不管try和catch块中代码的执行情况如何，程序都会进入到finally块中。

所以一个正常的异常处理过程应该如下所示：

```shell
try{
	//正常流程
}
catch(subException e){
	//异常处理块1
}
catch(subException e){
	//异常处理块2
}
...
finally{
	//资源回收
}
```

需要注意的是：在异常处理的语法结构中，只有try是必须的，catch和finally都是可选的，但是两者必须有一个出现。且catch快都应该在try后面，finally必须在catch（如果有的话）块后面。

# 2 学习总结

在使用多异常捕获的时候，要注意如果一个catch块中列举了多种异常，那么这些异常变量是有final修饰的，之前学习的时候没注意到这点，在写一些程序的时候就会编译错误。

# 3 明日计划

1. 复习throw和throws的使用
2. IO流

